trigger:
  branches:
    include:
      - main

pool:
  vmImage: "ubuntu-latest"

variables:
  buildConfiguration: "Release"

stages:
  - stage: Build
    jobs:
      - job: BuildAndTest
        steps:
          - task: UseDotNet@2
            inputs:
              packageType: "sdk"
              version: "8.x"

          - script: dotnet restore DocoPark1.slnx
            displayName: "Restore packages"

          - script: dotnet build DocoPark1.slnx --configuration $(buildConfiguration) --no-restore
            displayName: "Build solution"

          - script: dotnet publish DocoPark1/DocoParkWebApp.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
            displayName: "Publish"

          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: "$(Build.ArtifactStagingDirectory)"
              ArtifactName: "drop"
