// <auto-generated />
using System;
using DocoPark.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DocoPark.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260630130137_RemoveVehicleTypeFromParkingSpot")]
    partial class RemoveVehicleTypeFromParkingSpot
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DocoPark.Domain.Entities.ParkingSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CheckInTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ParkingSessions");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.ParkingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrentSessionId")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentSessionId1")
                        .HasColumnType("int");

                    b.Property<string>("SpotNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SpotStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CurrentSessionId1");

                    b.HasIndex("SpotNumber")
                        .IsUnique();

                    b.ToTable("ParkingSpots");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SpotNumber = "S001",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 2,
                            SpotNumber = "S002",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 3,
                            SpotNumber = "S003",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 4,
                            SpotNumber = "S004",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 5,
                            SpotNumber = "S005",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 6,
                            SpotNumber = "S006",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 7,
                            SpotNumber = "S007",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 8,
                            SpotNumber = "S008",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 9,
                            SpotNumber = "S009",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 10,
                            SpotNumber = "S010",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 11,
                            SpotNumber = "S011",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 12,
                            SpotNumber = "S012",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 13,
                            SpotNumber = "S013",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 14,
                            SpotNumber = "S014",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 15,
                            SpotNumber = "S015",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 16,
                            SpotNumber = "S016",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 17,
                            SpotNumber = "S017",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 18,
                            SpotNumber = "S018",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 19,
                            SpotNumber = "S019",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 20,
                            SpotNumber = "S020",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 21,
                            SpotNumber = "S021",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 22,
                            SpotNumber = "S022",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 23,
                            SpotNumber = "S023",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 24,
                            SpotNumber = "S024",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 25,
                            SpotNumber = "S025",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 26,
                            SpotNumber = "S026",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 27,
                            SpotNumber = "S027",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 28,
                            SpotNumber = "S028",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 29,
                            SpotNumber = "S029",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 30,
                            SpotNumber = "S030",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 31,
                            SpotNumber = "S031",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 32,
                            SpotNumber = "S032",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 33,
                            SpotNumber = "S033",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 34,
                            SpotNumber = "S034",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 35,
                            SpotNumber = "S035",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 36,
                            SpotNumber = "S036",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 37,
                            SpotNumber = "S037",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 38,
                            SpotNumber = "S038",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 39,
                            SpotNumber = "S039",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 40,
                            SpotNumber = "S040",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 41,
                            SpotNumber = "S041",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 42,
                            SpotNumber = "S042",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 43,
                            SpotNumber = "S043",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 44,
                            SpotNumber = "S044",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 45,
                            SpotNumber = "S045",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 46,
                            SpotNumber = "S046",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 47,
                            SpotNumber = "S047",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 48,
                            SpotNumber = "S048",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 49,
                            SpotNumber = "S049",
                            SpotStatus = "Available"
                        },
                        new
                        {
                            Id = 50,
                            SpotNumber = "S050",
                            SpotStatus = "Available"
                        });
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParkingSpotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReservedFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ReservedTo")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSpotId");

                    b.HasIndex("UserId");

                    b.HasIndex("VehicleId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("MonthlyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ParkingSessionId")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("SubscriptionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParkingSessionId");

                    b.HasIndex("SubscriptionId");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("IsPremium")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VehicleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.ParkingSession", b =>
                {
                    b.HasOne("DocoPark.Domain.Entities.ParkingSpot", "ParkingSpot")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocoPark.Domain.Entities.User", "User")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DocoPark.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("ParkingSessions")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.ParkingSpot", b =>
                {
                    b.HasOne("DocoPark.Domain.Entities.ParkingSession", "CurrentSession")
                        .WithMany()
                        .HasForeignKey("CurrentSessionId1");

                    b.Navigation("CurrentSession");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("DocoPark.Domain.Entities.ParkingSpot", "ParkingSpot")
                        .WithMany("Reservations")
                        .HasForeignKey("ParkingSpotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DocoPark.Domain.Entities.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DocoPark.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany("Reservations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSpot");

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Subscription", b =>
                {
                    b.HasOne("DocoPark.Domain.Entities.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("DocoPark.Domain.Entities.ParkingSession", "ParkingSession")
                        .WithMany("Transactions")
                        .HasForeignKey("ParkingSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DocoPark.Domain.Entities.Subscription", "Subscription")
                        .WithMany("Transactions")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DocoPark.Domain.Entities.User", "User")
                        .WithMany("Transactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ParkingSession");

                    b.Navigation("Subscription");

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Vehicle", b =>
                {
                    b.HasOne("DocoPark.Domain.Entities.User", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("User");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.ParkingSession", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.ParkingSpot", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Subscription", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.User", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("Reservations");

                    b.Navigation("Subscriptions");

                    b.Navigation("Transactions");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("DocoPark.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("ParkingSessions");

                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
